module.exports = {
  content: ['./*.html', './*.js'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "tertiary-container": "#8a4cfc",
              "on-secondary-fixed": "#181b28",
              "on-surface": "#181c20",
              "on-tertiary": "rgba(255, 255, 255, 0.7)",
              "surface-light": "#f0f2f8",
              "accent-blue": "#3b82f6",
              "surface-bright": "#F0F2F8",
              "surface-container": "#eceef4",
              "on-secondary": "rgba(255, 255, 255, 0.7)",
              "primary-fixed": "#e1e0ff",
              "surface-container-low": "#f2f3f9",
              "surface-container-high": "#e6e8ee",
              "on-error": "rgba(255, 255, 255, 0.7)",
              "on-primary-fixed-variant": "#2f2ebe",
              "surface-variant": "#e0e2e8",
              "primary-container": "#6063ee",
              "silk-bg": "#F0F2F8",
              "silk-blue": "#4A90E2",
              "silk-green": "#50E3C2",
              "on-tertiary-fixed": "#25005a",
              "background-base": "#e8eaf0",
              "on-tertiary-fixed-variant": "#5a00c6",
              "tertiary": "#712ae2",
              "inverse-on-surface": "#eff1f7",
              "on-tertiary-container": "#fffbff",
              "secondary-container": "#e0e1f4",
              "error": "#ba1a1a",
              "inverse-surface": "#2d3135",
              "on-error-container": "#93000a",
              "on-primary-fixed": "#07006c",
              "on-primary": "rgba(255, 255, 255, 0.7)",
              "primary": "#4648d4",
              "tertiary-fixed": "#eaddff",
              "primary-fixed-dim": "#c0c1ff",
              "surface-dim": "#d8dae0",
              "outline": "#767586",
              "surface-dark": "#d4d6dc",
              "on-background": "#181c20",
              "inverse-primary": "#c0c1ff",
              "on-surface-variant": "#464554",
              "accent-green": "#22c55e",
              "surface-container-lowest": "rgba(255, 255, 255, 0.7)",
              "on-secondary-fixed-variant": "#444655",
              "secondary-fixed-dim": "#c4c5d7",
              "outline-variant": "#c7c4d7",
              "on-secondary-container": "#616373",
              "tertiary-fixed-dim": "#d2bbff",
              "on-primary-container": "#fffbff",
              "background": "#F0F2F8",
              "surface": "#F0F2F8",
              "error-container": "#ffdad6",
              "text-primary": "#2e3040",
              "secondary-fixed": "#e0e1f4",
              "surface-tint": "#494bd6",
              "text-secondary": "#585a68",
              "surface-container-highest": "#e0e2e8",
              "accent-purple": "#a855f7",
              "secondary": "#5b5d6d",
              "neon-purple": "#A855F7",
              "neon-blue": "#3B82F6",
              "neon-green": "#22C55E"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px",
              "card": "32px",
              "neo": "32px"
      },
      "spacing": {
              "element-gap": "1rem",
              "container-padding": "1.5rem",
              "grid-gutter": "1.5rem",
              "stack-gap": "1.5rem",
              "section-margin": "2rem"
      },
      "fontFamily": {
              "title-sm": ["Plus Jakarta Sans"],
              "headline-md": ["Plus Jakarta Sans"],
              "display-lg": ["Plus Jakarta Sans"],
              "label-sm": ["Plus Jakarta Sans"],
              "body-md": ["Plus Jakarta Sans"],
              "sans": ["'Plus Jakarta Sans'", "sans-serif"],
              "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
              "label-md": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      "fontSize": {
              "title-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-md": ["20px", {"lineHeight": "1.3", "fontWeight": "700"}],
              "display-lg": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "500"}],
              "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      boxShadow: {
          "neumorphic": "6px 6px 12px #e3e6ee, -6px -6px 12px rgba(255, 255, 255, 0.7)",
          "neumorphic-inset": "inset 4px 4px 8px #e3e6ee, inset -4px -4px 8px rgba(255, 255, 255, 0.7)",
          'neo-raised': '6px 6px 12px rgba(0,0,0,0.08), -6px -6px 12px rgba(255,255,255,0.7)',
          'neo-inset': 'inset 4px 4px 8px rgba(0,0,0,0.06), inset -4px -4px 8px rgba(255,255,255,0.7)',
          'neo': '6px 6px 12px rgba(0,0,0,0.08), -6px -6px 12px rgba(255,255,255,0.7)',
          "neo-sm": "5px 5px 10px #D1D9E6, -5px -5px 10px rgba(255, 255, 255, 0.7)",
          "neo-pressed": "inset 5px 5px 10px #D1D9E6, inset -5px -5px 10px rgba(255, 255, 255, 0.7)",
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
